version: '3'

services:

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - persistence-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  cassandra:
    image: cassandra:latest
    volumes:
      - persistence-cassandra:/var/lib/cassandra
    ports:
      - "9042:9042"

volumes:
  persistence-postgres:
  persistence-cassandra:
